services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  social_network:
    build: .
    command:
      [
        "sh",
        "-c",
        "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000",
      ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

    environment:
      - POSTGRES_DB=social_network
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - PYTHONDONTWRITEBYTECODE=1

volumes:
  postgres_data:
